In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("winequality.csv")
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,1
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,2
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,3
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,4


In [3]:
df.isna().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
Id                      0
dtype: int64

In [4]:
df.drop(columns='Id',inplace=True)

In [6]:
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5


In [7]:
df.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

In [8]:
x=df[['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol']]
y=df['quality']

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
print(f"x_train : {x_train.shape}\nx_test : {x_test.shape}\ny_train : {y_train.shape}\ny_test : {y_test.shape}")

x_train : (914, 11)
x_test : (229, 11)
y_train : (914,)
y_test : (229,)


In [11]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)

,fit_intercept,True
,copy_X,True
,tol,1e-06
,n_jobs,None
,positive,False


In [12]:
m=lr.coef_
m

array([ 5.13430654e-02, -1.33625691e+00, -3.39100758e-01,  4.12143173e-03,
       -1.80653035e+00,  1.88076181e-03, -2.28305818e-03, -3.06532562e+01,
       -2.49236344e-01,  9.73040097e-01,  2.66586068e-01])

In [14]:
c=lr.intercept_
c

np.float64(34.209805578378685)

In [15]:
y_pred=lr.predict(x_test)
y_pred

array([5.37639096, 4.81275231, 5.26822711, 5.08826518, 6.09668676,
       6.60433542, 5.36417303, 5.06978794, 5.78461148, 5.32382095,
       6.31298023, 6.39721516, 5.3122581 , 6.20451475, 5.86121236,
       4.84318641, 5.69306745, 5.70473751, 5.50099506, 6.4022271 ,
       6.06476494, 6.03726349, 5.17366124, 6.50195777, 5.60352313,
       5.10641179, 6.56067549, 5.96071079, 5.10316054, 5.57954028,
       6.20303322, 5.47600319, 6.59869683, 5.73347337, 5.55058293,
       5.26541133, 5.48831034, 6.05771316, 6.95448756, 6.57961946,
       6.4526993 , 5.34213598, 7.03445013, 5.37970557, 5.05503642,
       5.0554158 , 5.61860118, 5.8525548 , 4.63668652, 5.68553779,
       6.42194262, 5.26381661, 5.60884518, 5.88146705, 5.78923411,
       6.38843403, 5.50237456, 5.70598277, 6.0421496 , 5.23069794,
       5.52701136, 5.95270183, 5.60755482, 6.35884408, 6.15031671,
       5.38044967, 6.86150613, 5.26208169, 4.8615088 , 5.98738066,
       5.74523457, 5.33651712, 5.93642512, 5.94447105, 5.18598

In [16]:
from sklearn.metrics import mean_squared_error
print(mean_squared_error(y_test,y_pred))

0.38003245026277577


In [18]:
y=lr.predict([[8,0.4,0.40,.15,0.048,40,150,0.99,3,0.45,10.5]])
y

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([5.73967259])